# Generated by Django 5.1 on 2024-08-19 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Plats', 'Plats'), ('Dessert', 'Dessert'), ('Boisson', 'Boisson')], max_length=20)),
                ('subCategories', models.CharField(max_length=20)),
                ('rating', models.FloatField()),
                ('isRecomanded', models.BooleanField()),
                ('isRecent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingrédients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=10)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrédients', to='Recipe.plats')),
            ],
        ),
        migrations.CreateModel(
            name='Préparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('description', models.TextField()),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='préparation', to='Recipe.plats')),
            ],
        ),
        migrations.CreateModel(
            name='Utils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utils', to='Recipe.plats')),
            ],
        ),
    ]
