# Generated by Django 5.1 on 2024-08-19 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ingrédients',
            name='plat',
        ),
        migrations.RemoveField(
            model_name='utils',
            name='plat',
        ),
        migrations.AddField(
            model_name='plats',
            name='ingrédients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Plats', to='Recipe.ingrédients'),
        ),
        migrations.AddField(
            model_name='plats',
            name='préparation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Plats', to='Recipe.preparation'),
        ),
        migrations.DeleteModel(
            name='Préparation',
        ),
    ]
