# Generated by Django 5.1 on 2024-08-19 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0002_preparation_remove_ingrédients_plat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plats',
            name='ingrédients',
        ),
        migrations.RemoveField(
            model_name='plats',
            name='préparation',
        ),
        migrations.AddField(
            model_name='ingrédients',
            name='plat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='Recipe.plats'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='plat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preparation', to='Recipe.plats'),
        ),
        migrations.AddField(
            model_name='utils',
            name='plat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utils', to='Recipe.plats'),
        ),
    ]
