# Generated by Django 5.1 on 2024-08-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0003_remove_plats_ingrédients_remove_plats_préparation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utils',
            name='plat',
        ),
        migrations.AddField(
            model_name='utils',
            name='plat',
            field=models.ManyToManyField(null=True, related_name='utils', to='Recipe.plats'),
        ),
    ]
