# Generated by Django 5.1 on 2024-08-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0004_remove_utils_plat_utils_plat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utils',
            name='plat',
        ),
        migrations.AddField(
            model_name='plats',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='plats',
            name='utils',
            field=models.ManyToManyField(null=True, related_name='utils', to='Recipe.utils'),
        ),
    ]
