# Generated by Django 5.1 on 2024-08-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0005_remove_utils_plat_plats_date_plats_utils'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plats',
            name='isRecent',
        ),
        migrations.RemoveField(
            model_name='plats',
            name='isRecomanded',
        ),
        migrations.RemoveField(
            model_name='plats',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='plats',
            name='subCategories',
        ),
    ]
