# Generated by Django 5.1 on 2024-08-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0008_plats_rate_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plats',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
