# Generated by Django 5.1 on 2024-09-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0010_rating_author_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='plats',
            name='image',
            field=models.FileField(null=True, upload_to='image/'),
        ),
    ]
